Script is now in perl and uses the pidfile instead os ps -aef

diff --git a/startsynchronetbbs b/startsynchronetbbs
--- a/startsynchronetbbs
+++ b/startsynchronetbbs
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/perl
 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -14,25 +14,56 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 
-export SBBSDIR=/sbbs
-export SBBSCTRL=$SBBSDIR/ctrl
-export PATH=$SBBSDIR/exec:$PATH
-export TERM=xterm-256color
+my $SBBSDIR = "/sbbs";
+my $PIDFILE = "/var/run/sbbs.pid";
+my $SCREENCMD = "/usr/bin/screen";
 
-while :
-do
-cd $SBBSDIR
-running=`ps ax|grep sbbs|grep -v grep`
-if [ -z "$running" ]; then
-    # See if they want the server started
-    if [ ! -f "$SBBSDIR/nostart" ]; then
-       # The Log Entry
-       TIME="SBBS Down, Restarting: `date +"%A, %B %d - %r"`"
-       echo $TIME >>$SBBSDIR/SBBSScreen.log
-       cd $SBBSDIR
-       screen -fa -S SBBS -d -U -m sbbs
-    fi
-fi
-       sleep 600
-done
-exit 0
+# No changes below here...
+
+my $pidnum = "";
+my $startpath = $ENV{'PATH'};
+my $newpath = "$SBBSDIR/exec:$startpath";
+
+# Set ENV vars
+$ENV{'PATH'} = $newpath;
+$ENV{'SBBSCTRL'} = "$SBBSDIR/ctrl";
+$ENV{'TERM'} = "xterm-256color";
+
+# Get the SBBS process pid
+open(INPF, "<$PIDFILE") || die "Unable to open $PIDFILE for input";
+{
+        local $/;
+        $pidnum = <INPF>;
+}
+close(INPF);
+
+while (-1)
+{
+	chdir $SBBSDIR;
+	my $running="";
+	# check if BBS process is running
+	my $exists = kill 0, $pidnum;
+	if ($exists)
+	{
+		$running = "running";
+	}
+
+	if ($running ne "running")
+	{
+		# See if they want the server started
+		if (! -f "$SBBSDIR/nostart")
+		{
+			# The Log Entry
+			my $datestring = localtime();
+			my $TIME="SBBS Down, Restarting: $datestring";
+			open(OUTF, ">>$SBBSDIR/SBBSScreen.log") || die "Unable to open $SBBSDIR/SBBSScreen.log for appending";
+			print (OUTF "$TIME\n");
+			close($OUTF);
+			chdir $SBBSDIR;
+			system("$SCREENCMD -fa -S SBBS -d -U -m sbbs");
+		}
+	}
+	# Sleep for 5 minutes before checking again
+	sleep(300);
+}
+exit(0);
