All scripts now in perl, and the scripts actually work ;)

diff --git a/synchronetbbs b/synchronetbbs
--- a/synchronetbbs
+++ b/synchronetbbs
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/perl
 
 ### BEGIN INIT INFO
 # Provides:          synchronetbbs
@@ -28,34 +28,90 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 
-export SBBSDIR=/sbbs
-case "$1" in
+my $SBBSDIR = "/sbbs";
+my $PIDFILE = "/var/run/sbbs.pid";
+my $pidnum = "";
 
-start)		echo "Starting SBBS... "
-		if [ -f "$SBBSDIR/nostart" ]; then
+# Get the SBBS process pid
+if (-f $PIDFILE)
+{
+	open(INPF, "<$PIDFILE") || die "Unable to open $PIDFILE for input";
+	{
+        	local $/;
+        	$pidnum = <INPF>;
+	}
+	close(INPF);
+}
+else
+{
+	$pidnum = "nofile";
+}
+
+my $Command = $ARGV[0];
+
+my $running="";
+# check if BBS process is running
+my $exists = "";
+if ($pidnum ne "nofile")
+{
+	$exists = kill 0, $pidnum;
+	if ($exists)
+	{
+		$running = "running";
+	}
+}
+if (($Command eq "") || ($Command eq "start"))
+{
+	if ($running ne "running")
+	{
+		print "Starting SBBS...\n";
+		if (-f "$SBBSDIR/nostart")
+		{
+			print "Removing $SBBSDIR/nostart\n";
 			# Remove the lock file if it exists
-			rm "$SBBSDIR/nostart"
-		fi
+			unlink("$SBBSDIR/nostart");
+		}
 		# Start the screen process
-		nohup $SBBSDIR/startsynchronetbbs > /tmp/SBBSStartup.log&
-		;;
-stop)		echo "Stopping SBBS process... "
-		touch "$SBBSDIR/nostart"
-		killall sbbs
-		exit 1
-		;;
-restart)        $0 stop
-		rm "$SBBSDIR/nostart"
-                ;;
-status)		running=`ps ax|grep sbbs|grep -v grep`
-		if [ ! -z "$running" ]; then
-			echo "SBBS Server Running"
-		else
-			echo "SBBS Server Not Running"
-		fi
-		;;
-*)              echo "Usage: $0 {start|status|stop|restart}"
-                exit 1
-                ;;
-esac
-exit 0
+		system("nohup $SBBSDIR/startsynchronetbbs > /tmp/SBBSStartup.log\&");
+	}
+}
+elsif ($Command eq "stop")
+{
+	print "Stopping SBBS process...\n";
+	system("touch '$SBBSDIR/nostart'");
+	if ($running eq "running")
+	{
+		kill 'HUP', $pidnum;
+	}
+}
+elsif ($Command eq "restart")
+{
+	if (-f "$SBBSDIR/nostart")
+	{
+		print("Removing $SBBSDIR/nostart\n");
+		unlink("$SBBSDIR/nostart");
+	}
+	if ($running eq "running")
+	{
+		kill 'HUP', $pidnum;
+	}
+}
+elsif ($Command eq "status")
+{
+	if ($running eq "running")
+	{
+		print("SBBS Server Running\n");
+	}
+	else
+	{
+		print("SBBS Server Not Running\n");
+	}
+}
+else
+{
+	print ("Uknown command '$Command'\n");
+	print ("Usage: $0 {start|status|stop|restart}");
+	exit(1);
+}
+
+exit(0);
